# -*- coding: utf-8 -*-
# ruff: noqa
# mypy: ignore-errors
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x1atask_cascadence.ume.protos\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n\x08TaskSpec\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tuser_hash\x18\x04 \x01(\t\"\xd1\x01\n\x07TaskRun\x12\x32\n\x04spec\x18\x01 \x01(\x0b\x32$.task_cascadence.ume.protos.TaskSpec\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12.\n\nstarted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x66inished_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tuser_hash\x18\x06 \x01(\t\"0\n\x0bTaskPointer\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x11\n\tuser_hash\x18\x02 \x01(\t\"E\n\rPointerUpdate\x12\x11\n\ttask_name\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\x12\x11\n\tuser_hash\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASKSPEC._serialized_start=76
  _TASKSPEC._serialized_end=152
  _TASKRUN._serialized_start=155
  _TASKRUN._serialized_end=364
  _TASKPOINTER._serialized_start=366
  _TASKPOINTER._serialized_end=414
  _POINTERUPDATE._serialized_start=416
  _POINTERUPDATE._serialized_end=485
# @@protoc_insertion_point(module_scope)
