name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Check for code changes
        id: code_changes
        run: |
          git fetch --depth=1 origin ${{ github.event.before }}
          CHANGED=$(git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} -- '*.py' |
            grep '^+' |
            grep -v '^+++' |
            grep -v '^+\s*#' |
            grep -v '^+\s*$' | wc -l)
          echo "count=$CHANGED" >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        if: steps.code_changes.outputs.count != '0'
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest pytest-cov tzdata
          pip install -e .
      - name: Run ruff check
        if: steps.code_changes.outputs.count != '0'
        run: ruff check .
      - name: Run tests
        if: steps.code_changes.outputs.count != '0'
        run: pytest
